### PR TITLE
add support for shared_ptr casts

### PR DESCRIPTION
**Pull request by Smattr**
Note that this commit also introduces a new config variable, cpp_no_cpp17.

Thanks for providing this syntax file. Please let me know if you want any adjustments to the patch.

### CODE REVIEW

**Comment by mattn** [comment]
The keywords are already in vim's syntax/cpp.vim

**Comment by Smattr** [comment]
Sorry, I think I'm misunderstanding something. I can't see anything in [Vim's cpp.vim](https://github.com/vim/vim/blob/master/runtime/syntax/cpp.vim) or upstream in [this repo's cpp.vim](https://github.com/vim-jp/vim-cpp/blob/master/syntax/cpp.vim) that supports shared_ptr cast like `dynamic_pointer_cast`. Can you link to where these keywords exist?

**Comment by mattn** [comment]
Right, sorry. Will merge in later.

**Comment by mattn** [comment]
Thanks

**Pull request merged**
