### PR TITLE
fix #46

### LINKED ISSUE #46: Wrong coloring in `hi Float`
Both in `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 26 2017 07:49:10)` and `NVIM 0.2.0` --which both rely on the `2016 Oct 28` version of this project for syntax highlighting of cpp files -- seem to color floats wrong.

Example:
In my color scheme I'm using:
`hi Float guifg=#eb2121 guibg=NONE guisp=NONE gui=NONE`
`hi Number guifg=#f0ad6d guibg=NONE guisp=NONE gui=NONE`
see https://github.com/originalsouth/nvimrc/blob/master/colors/inkpot.vim

This produces wrong coloring of statement like `printf("%g\n",1.0+1.0);` colors the `1` as defined by `hi Number` and the `.0` as defined by `hi Float` both in VIM as NVIM.

See image for example: `c` left, `cpp` right (the `1` is yellowish where the `.0` is reddish):
vim8 0-hi-float

nvim0 2 0-hi-float

This seems to be a regression from the `2015 Nov 10` version.
Where the coloring is still ok. See image:
nvim0 1 7-hi-float

See also [this issue](https://github.com/neovim/neovim/issues/6711) in the neovim repository.

### PR DESCRIPTION
**Pull request by h-east**
How about this?

### CODE REVIEW

**Comment by mattn** [comment]
How about just add contains like below?

```diff
diff --git a/syntax/cpp.vim b/syntax/cpp.vim
index 5a478fb..495a335 100644
--- a/syntax/cpp.vim
+++ b/syntax/cpp.vim
@@ -48,7 +48,7 @@ endif
 if !exists("cpp_no_cpp14")
   syn case ignore
   syn match cppNumber		display "\<0b[01]\('\=[01]\+\)*\(u\=l\{0,2}\|ll\=u\)\>"
-  syn match cppNumber		display "\<[1-9]\('\=\d\+\)*\(u\=l\{0,2}\|ll\=u\)\>"
+  syn match cppNumber		display "\<[1-9]\('\=\d\+\)*\(u\=l\{0,2}\|ll\=u\)\>" contains=cFloat
   syn match cppNumber		display "\<0x\x\('\=\x\+\)*\(u\=l\{0,2}\|ll\=u\)\>"
   syn case match
 endif
```

**Comment by h-east** [comment]
@mattn Your solution is best for me:+1:

**Comment by originalsouth** [comment]
This solution works for me :+1:

**Comment by mattn** [comment]
closed by #48

**Pull request closed without merging**
