### PR TITLE
Add __VA_ARGS__ as constant

### PR DESCRIPTION
**Pull request by h-east**

### CODE REVIEW

**Comment by mattn** [comment]
LGTM but way other's. ping @osyo-manga @rhysd

**Comment by rhysd** [comment]
Nice catch :+1:

**Comment by osyo-manga** [comment]
+1

**Comment by mattn** [comment]
:metal:

**Comment by mattn** [comment]
I'll send the patch to vim-dev in later.

**Comment by h-east** [comment]
Thanks! :cat2::dash:

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/_GeLfk5sdcI

**Pull request merged**
