### PR TITLE
add keyword restrict

### PR DESCRIPTION
**Pull request by mattn**
@rhysd @osyo-manga do you have something tought?

### CODE REVIEW

**Comment by rhysd** [comment]
Although my understanding may not be correct, `restrict` was firstly added to C99.  So, I think it should be added to `syntax/c.vim`.

**Comment by rhysd** [comment]
I looked into it more.

`restrict` is in [C99 keywords](http://en.cppreference.com/w/c/keyword) but not in [C++ keywords](http://en.cppreference.com/w/cpp/keyword).  So I think it is best that `restrict` is highlighted as keyword in C but not highlighted in C++.

**Comment by rhysd** [comment]
I think [this condition](https://github.com/vim-jp/vim-cpp/blob/master/syntax/c.vim#L267) should be fixed to `!exists("c_no_c99") && s:ft !=# 'cpp'`.

**Comment by mattn** [comment]
Ah, he says highlighting restrict keyword in C++ is bad.

https://github.com/vim/vim/issues/623

okay, I'll suggest your change to bram.

thanks

**Comment by rhysd** [comment]
:+1:

**Pull request closed without merging**
